'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import Navbar from '@/components/Navbar';
import StatsSection from '@/components/StatsSection';
import SaaSPreview from '@/components/SaaSPreview';
import Logo from '@/components/Logo';
import {
  Cpu,
  Layers,
  Activity,
  Compass,
  Flame,
  Award,
  BookOpen,
  Sparkles,
  Code,
  ArrowRight,
  MessageSquare,
  Mail,
  Star,
  Zap,
} from 'lucide-react';

export default function LandingPage() {
  const router = useRouter();

  // Stagger wrapper variant
  const containerVariants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  // Upward slide variant
  const itemVariants = {
    hidden: { y: 25, opacity: 0 },
    show: {
      y: 0,
      opacity: 1,
      transition: { type: 'spring', stiffness: 100, damping: 18 },
    },
  };

  // Course mockup data
  const courses = [
    {
      title: 'Next.js Masterclass',
      lessons: 32,
      progress: 75,
      difficulty: 'Advanced',
      duration: '12h',
      icon: Layers,
      color: 'from-purple-500 to-indigo-600',
    },
    {
      title: 'AI & Prompt Engineering',
      lessons: 18,
      progress: 45,
      difficulty: 'Intermediate',
      duration: '6h',
      icon: Cpu,
      color: 'from-cyan-400 to-blue-600',
    },
    {
      title: 'Full Stack Development',
      lessons: 45,
      progress: 20,
      difficulty: 'Beginner',
      duration: '24h',
      icon: Code,
      color: 'from-pink-500 to-purple-600',
    },
  ];

  // Bento grid feature cards
  const bentoFeatures = [
    {
      title: 'AI Mentor',
      desc: 'Get 24/7 personalized study assistance, instant feedback, and tailored learning materials generated by AI.',
      icon: Cpu,
      span: 'lg:col-span-2',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(34,211,238,0.25)]',
    },
    {
      title: 'Learning Dashboard',
      desc: 'Track active courses, achievements, and milestones through a highly visual personalized workspace.',
      icon: Layers,
      span: 'lg:col-span-1',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(139,92,246,0.25)]',
    },
    {
      title: 'Progress Tracking',
      desc: 'Visualize your academic path with precision graphs, completion wheels, and detailed session analysis.',
      icon: Activity,
      span: 'lg:col-span-1',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(168,85,247,0.25)]',
    },
    {
      title: 'Smart Recommendations',
      desc: 'Receive automated next-step course suggestions based on your study habits and goal milestones.',
      icon: Compass,
      span: 'lg:col-span-2',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(34,211,238,0.25)]',
    },
    {
      title: 'Learning Streaks',
      desc: 'Build consistent daily habits with flame metrics and streak completion bonuses.',
      icon: Flame,
      span: 'lg:col-span-1.5',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(249,115,22,0.25)]',
    },
    {
      title: 'Achievement System',
      desc: 'Earn experience points (XP) and unlock specialized badges representing your scholar level status.',
      icon: Award,
      span: 'lg:col-span-1.5',
      glow: 'group-hover:shadow-[0_0_30px_-5px_rgba(139,92,246,0.25)]',
    },
  ];

  // Testimonial cards
  const testimonials = [
    {
      name: 'Sarah Jenkins',
      role: 'Frontend Engineer',
      text: 'The AI Mentor transformed how I study. I went from struggling with Next.js configurations to deploying full applications in weeks!',
      avatar: 'SJ',
    },
    {
      name: 'David Chen',
      role: 'Computer Science Student',
      text: 'I love the learning streaks! Building consistency was always my biggest issue, but the gamified XP tracking makes me want to study every day.',
      avatar: 'DC',
    },
    {
      name: 'Elena Rostova',
      role: 'Self-Taught Developer',
      text: 'Having a single dashboard that visualizes study hours and progress alongside premium coursework is exactly what self-learners need.',
      avatar: 'ER',
    },
  ];

  return (
    <div className="min-h-screen bg-[#050816] text-white flex flex-col overflow-x-hidden selection:bg-brand-purple/30 selection:text-white">
      {/* Background celestial styling */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(139,92,246,0.12)_0%,transparent_50%)] pointer-events-none" />
      <div className="absolute top-[120vh] left-[-20%] w-[60%] h-[50vh] bg-[radial-gradient(circle,rgba(34,211,238,0.03)_0%,transparent_70%)] pointer-events-none" />
      <div className="absolute top-[220vh] right-[-20%] w-[60%] h-[50vh] bg-[radial-gradient(circle,rgba(168,85,247,0.03)_0%,transparent_70%)] pointer-events-none" />

      {/* Sticky Header Navbar */}
      <Navbar />

      {/* 1. HERO SECTION */}
      <section className="relative pt-32 pb-16 lg:pt-48 lg:pb-24 max-w-7xl mx-auto px-6 w-full text-center flex flex-col items-center gap-8">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.5 }}
          className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-brand-purple text-xs font-black uppercase tracking-widest"
        >
          <Sparkles size={14} className="animate-pulse" />
          <span>🚀 AI-Powered Learning Platform</span>
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ type: 'spring', stiffness: 100, damping: 15 }}
          className="text-5xl sm:text-6xl md:text-7xl font-black tracking-tight leading-[1.05] max-w-4xl"
        >
          Master Skills.<br />
          Track Progress.<br />
          <span className="bg-gradient-to-r from-brand-purple via-violet-400 to-brand-cyan bg-clip-text text-transparent">
            Learn With AI.
          </span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15, duration: 0.6 }}
          className="text-zinc-400 text-base sm:text-lg max-w-2xl leading-relaxed"
        >
          Transform your learning journey with personalized learning paths, intelligent analytics, AI study assistance, and progress tracking built for modern students.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25, duration: 0.5 }}
          className="flex flex-col sm:flex-row gap-4 mt-4"
        >
          <button
            onClick={() => router.push('/login?mode=signup')}
            className="px-8 py-4 bg-brand-purple hover:bg-purple-600 text-sm font-extrabold uppercase tracking-wider rounded-full shadow-lg shadow-purple-950/40 transition-all flex items-center justify-center gap-2 cursor-pointer"
          >
            <span>Start Learning</span>
            <ArrowRight size={16} />
          </button>
          <button
            onClick={() => router.push('/login')}
            className="px-8 py-4 bg-white/5 border border-white/10 hover:bg-white/10 text-sm font-extrabold uppercase tracking-wider rounded-full transition-all cursor-pointer"
          >
            Explore Dashboard
          </button>
        </motion.div>
      </section>

      {/* 2. STATS SECTION (Viewport-triggered Counters) */}
      <StatsSection />

      {/* 3. SAAS DASHBOARD PREVIEW */}
      <section className="py-16 lg:py-24 border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 text-center mb-12">
          <span className="text-xs font-extrabold tracking-widest text-brand-purple uppercase">Intuitive Workspace</span>
          <h2 className="text-3xl sm:text-4xl font-black text-white tracking-tight mt-2">Interactive Dashboard Experience</h2>
        </div>
        <SaaSPreview />
      </section>

      {/* 4. WHY CHOOSE NEXGEN LEARN (Bento Grid) */}
      <section id="features" className="py-20 lg:py-28 border-b border-white/5 relative">
        <div className="max-w-7xl mx-auto px-6 text-center mb-16 space-y-3">
          <span className="text-xs font-extrabold tracking-widest text-brand-cyan uppercase">Core Ecosystem</span>
          <h2 className="text-4xl font-black text-white tracking-tight">Why Students Choose NexGen Learn</h2>
          <p className="text-zinc-500 text-sm max-w-md mx-auto">
            Harness the power of machine learning, game theory, and beautiful data visualization to make studying intuitive.
          </p>
        </div>

        {/* Bento Grid */}
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {bentoFeatures.map((feat, idx) => {
            const Icon = feat.icon;
            return (
              <motion.div
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: '-50px' }}
                transition={{ duration: 0.5, delay: idx * 0.05 }}
                whileHover={{ y: -4, borderColor: 'rgba(168,85,247,0.2)' }}
                className={`bg-zinc-950/45 border border-white/5 rounded-3xl p-6 backdrop-blur-sm flex flex-col justify-between min-h-[220px] transition-all duration-300 group cursor-pointer ${feat.span} ${feat.glow}`}
              >
                <div className="flex items-center gap-3">
                  <div className="p-3 bg-white/5 border border-white/5 rounded-2xl text-brand-purple group-hover:text-brand-cyan transition-colors duration-300">
                    <Icon size={20} />
                  </div>
                  <h3 className="text-base sm:text-lg font-bold text-white tracking-tight group-hover:text-purple-200 transition-colors">
                    {feat.title}
                  </h3>
                </div>
                <p className="text-zinc-400 text-xs sm:text-sm mt-4 leading-relaxed flex-1">
                  {feat.desc}
                </p>
                <div className="mt-6 flex items-center gap-1.5 text-[10px] font-bold uppercase tracking-wider text-brand-purple group-hover:text-brand-cyan transition-colors">
                  <span>Learn more</span>
                  <ArrowRight size={10} className="transform group-hover:translate-x-0.5 transition-transform" />
                </div>
              </motion.div>
            );
          })}
        </div>
      </section>

      {/* 5. PREMIUM COURSE SHOWCASE */}
      <section id="courses" className="py-20 lg:py-28 border-b border-white/5">
        <div className="max-w-7xl mx-auto px-6 text-center mb-16 space-y-3">
          <span className="text-xs font-extrabold tracking-widest text-brand-purple uppercase">Curriculum</span>
          <h2 className="text-4xl font-black text-white tracking-tight">Explore Premium Courses</h2>
          <p className="text-zinc-500 text-sm max-w-md mx-auto">
            Deep-dive into tech-focused courses with dynamic progress tracking and embedded exercises.
          </p>
        </div>

        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-6">
          {courses.map((course, idx) => {
            const Icon = course.icon;
            return (
              <motion.article
                key={idx}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: idx * 0.1 }}
                whileHover={{ y: -6, borderColor: 'rgba(34,211,238,0.25)' }}
                className="bg-zinc-950/45 border border-white/5 rounded-3xl p-6 backdrop-blur-sm flex flex-col justify-between min-h-[280px] overflow-hidden group cursor-pointer transition-all duration-300"
              >
                <div className="space-y-4">
                  <div className="flex justify-between items-start">
                    <div className={`p-3.5 bg-gradient-to-tr ${course.color} rounded-2xl text-white shadow-lg`}>
                      <Icon size={22} />
                    </div>
                    <span className="text-[10px] font-bold text-brand-cyan border border-brand-cyan/20 px-2 py-0.5 rounded-full uppercase tracking-wider bg-cyan-500/5">
                      {course.difficulty}
                    </span>
                  </div>

                  <h3 className="text-lg font-black text-white tracking-tight group-hover:text-cyan-200 transition-colors">
                    {course.title}
                  </h3>
                  <div className="flex gap-4 text-xs text-zinc-500 font-semibold">
                    <span>📚 {course.lessons} Lessons</span>
                    <span>⏱️ {course.duration} Hours</span>
                  </div>
                </div>

                {/* Progress mock */}
                <div className="mt-8 space-y-2">
                  <div className="flex justify-between text-[10px] font-bold">
                    <span className="text-zinc-500">Progress Preview</span>
                    <span className="text-white">{course.progress}%</span>
                  </div>
                  <div className="h-1.5 w-full bg-zinc-900 border border-white/5 rounded-full overflow-hidden">
                    <div className={`h-full bg-gradient-to-r ${course.color} rounded-full`} style={{ width: `${course.progress}%` }} />
                  </div>
                </div>
              </motion.article>
            );
          })}
        </div>
      </section>

      {/* 6. GLASSMORPHIC TESTIMONIALS */}
      <section className="py-20 lg:py-28 border-b border-white/5 relative">
        <div className="max-w-7xl mx-auto px-6 text-center mb-16 space-y-3">
          <span className="text-xs font-extrabold tracking-widest text-brand-cyan uppercase">Success Stories</span>
          <h2 className="text-4xl font-black text-white tracking-tight">Loved by Self-Taught Students</h2>
        </div>

        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.map((test, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: idx * 0.1 }}
              whileHover={{ y: -4, borderColor: 'rgba(168,85,247,0.2)' }}
              className="bg-zinc-950/30 border border-white/5 rounded-3xl p-6 backdrop-blur-md flex flex-col justify-between min-h-[200px] transition-all duration-300 relative group cursor-pointer"
            >
              {/* Stars decoration */}
              <div className="flex gap-1 mb-4 text-brand-purple group-hover:text-brand-cyan transition-colors">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} size={12} fill="currentColor" />
                ))}
              </div>

              <p className="text-zinc-400 text-xs sm:text-sm leading-relaxed mb-6 flex-1">
                "{test.text}"
              </p>

              <div className="flex items-center gap-3 border-t border-white/5 pt-4">
                <div className="w-9 h-9 rounded-full bg-gradient-to-tr from-brand-purple to-brand-blue flex items-center justify-center font-bold text-white text-xs">
                  {test.avatar}
                </div>
                <div className="text-left flex flex-col">
                  <span className="text-xs font-bold text-white">{test.name}</span>
                  <span className="text-[10px] text-zinc-500 font-semibold">{test.role}</span>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* 7. MODERN INTERACTIVE CONTACT AREA */}
      <section id="contact" className="py-20 lg:py-28 relative">
        <div className="max-w-7xl mx-auto px-6 text-center mb-16 space-y-3">
          <span className="text-xs font-extrabold tracking-widest text-brand-purple uppercase">Connect</span>
          <h2 className="text-4xl font-black text-white tracking-tight">Join the NexGen Community</h2>
          <p className="text-zinc-500 text-sm max-w-md mx-auto">
            Interact with mentors, share study milestones, or get support through our custom channels.
          </p>
        </div>

        <div className="max-w-4xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 gap-4">
          {[
            { label: 'Discord Community', details: 'chat.nexgenlearn.com', icon: <MessageSquare size={24} className="mt-2" />, color: 'hover:border-purple-500/40 hover:bg-purple-500/5 hover:shadow-[0_0_24px_rgba(168,85,247,0.15)] text-brand-purple' },
            { label: 'GitHub Repository', details: 'github.com/nexgenlearn', icon: <svg className="w-6 h-6 mt-2 text-white" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.438 9.8 8.205 11.385.6.11.82-.26.82-.577v-2.234c-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.43.372.82 1.102.82 2.222v3.293c0 .319.22.694.825.576C20.565 21.795 24 17.3 24 12c0-6.63-5.37-12-12-12z"/></svg>, color: 'hover:border-white/20 hover:bg-white/5 hover:shadow-[0_0_24px_rgba(255,255,255,0.08)] text-white' },
            { label: 'LinkedIn Page', details: 'linkedin.com/company/nexgen', icon: <svg className="w-6 h-6 mt-2 text-brand-blue" viewBox="0 0 24 24" fill="currentColor"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>, color: 'hover:border-blue-500/40 hover:bg-blue-500/5 hover:shadow-[0_0_24px_rgba(59,130,246,0.15)] text-brand-blue' },
            { label: 'Direct Support', details: 'support@nexgenlearn.com', icon: <Mail size={24} className="mt-2" />, color: 'hover:border-cyan-500/40 hover:bg-cyan-500/5 hover:shadow-[0_0_24px_rgba(34,211,238,0.15)] text-brand-cyan' },
          ].map((card, idx) => {
            return (
              <motion.a
                href="#"
                key={idx}
                initial={{ opacity: 0, scale: 0.95 }}
                whileInView={{ opacity: 1, scale: 1 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: idx * 0.08 }}
                className={`bg-zinc-950/45 border border-white/5 rounded-2xl p-5 flex flex-col items-center text-center justify-between min-h-[150px] cursor-pointer transition-all duration-300 ${card.color}`}
              >
                {card.icon}
                <div className="flex flex-col gap-1 mt-4">
                  <span className="text-[10px] text-zinc-500 font-extrabold uppercase tracking-wider">{card.label}</span>
                  <span className="text-[11px] font-bold text-white truncate max-w-[150px]">{card.details}</span>
                </div>
              </motion.a>
            );
          })}
        </div>
      </section>

      {/* 8. FOOTER */}
      <footer className="w-full max-w-7xl mx-auto px-6 py-12 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-8 mt-auto relative z-10">
        <div className="flex flex-col items-center md:items-start text-center md:text-left gap-2">
          <Logo showTagline={true} size="md" />
        </div>

        {/* Links */}
        <div className="flex flex-wrap justify-center gap-8 text-xs font-semibold text-zinc-500 uppercase tracking-wider">
          <a href="#features" className="hover:text-zinc-300">Features</a>
          <a href="#courses" className="hover:text-zinc-300">Courses</a>
          <a href="/login" className="hover:text-zinc-300">Dashboard</a>
          <a href="#contact" className="hover:text-zinc-300">Contact</a>
        </div>

        {/* Social Icons */}
        <div className="flex gap-4 text-zinc-500">
          <a href="#" className="p-2 bg-white/5 hover:bg-white/10 rounded-full hover:text-white transition-all flex items-center justify-center w-8 h-8">
            <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0C5.37 0 0 5.37 0 12c0 5.3 3.438 9.8 8.205 11.385.6.11.82-.26.82-.577v-2.234c-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.43.372.82 1.102.82 2.222v3.293c0 .319.22.694.825.576C20.565 21.795 24 17.3 24 12c0-6.63-5.37-12-12-12z"/></svg>
          </a>
          <a href="#" className="p-2 bg-white/5 hover:bg-white/10 rounded-full hover:text-white transition-all flex items-center justify-center w-8 h-8">
            <svg className="w-4 h-4" viewBox="0 0 24 24" fill="currentColor"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
          </a>
          <a href="#" className="p-2 bg-white/5 hover:bg-white/10 rounded-full hover:text-white transition-all flex items-center justify-center w-8 h-8">
            <MessageSquare size={16} />
          </a>
        </div>
      </footer>
    </div>
  );
}
